const ProUI = {
  root:null, nav:null, panel:null, toastHost:null, bossPanel:null, worldCard:null, baseCard:null, buildTray:null,
  activePanel:null, initialized:false,
  icons:{ home:'⌂', tower:'◈', merge:'✧', collection:'▦', quest:'✪', world:'◌' },
  init(){ if(this.initialized) return this; this._base={hp:100,maxHp:100}; this._injectStyles(); this._build(); this._bind(); this.initialized=true; this.update(); this.updateWorld(); return this; },
  _injectStyles(){ if(document.getElementById('pro-ui-style')) return; const s=document.createElement('style'); s.id='pro-ui-style'; s.textContent=`
  :root{--p-bg:rgba(7,13,24,.82);--p-panel:rgba(8,16,29,.96);--p-line:rgba(255,255,255,.09);--p-text:#eff6ff;--p-muted:#91a4bf;--p-cyan:#63e6ff;--p-gold:#ffd166;--p-purple:#a98cff;--p-red:#ff6b7c;}
  *{box-sizing:border-box} button{font:inherit}
  #pro-ui{position:fixed;inset:0;pointer-events:none;z-index:80;color:var(--p-text);font-family:Inter,system-ui,-apple-system,'Segoe UI',sans-serif}
  .pro-top{position:absolute;top:max(10px,env(safe-area-inset-top));left:10px;right:10px;display:grid;grid-template-columns:1fr auto 1fr;gap:8px;align-items:start}
  .pro-card{background:linear-gradient(180deg,rgba(14,29,48,.92),rgba(6,13,24,.9));border:1px solid var(--p-line);box-shadow:0 10px 32px rgba(0,0,0,.24),inset 0 1px rgba(255,255,255,.05);backdrop-filter:blur(16px);border-radius:16px}
  .pro-status{padding:9px 12px;min-width:0}.pro-status .label{font-size:10px;color:var(--p-muted);text-transform:uppercase;letter-spacing:.12em}.pro-status .value{font-size:15px;font-weight:900;margin-top:2px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.pro-xp{margin-top:6px;height:5px;background:rgba(255,255,255,.07);border-radius:99px;overflow:hidden}.pro-xp>i{display:block;height:100%;width:0;background:linear-gradient(90deg,var(--p-cyan),var(--p-purple))}
  .pro-wave{text-align:center;padding:9px 16px;min-width:130px}.pro-wave b{display:block;font-size:13px}.pro-wave span{display:block;color:#bfe6ff;font-size:10px;margin-top:2px}
  .pro-world{justify-self:end;padding:8px 11px;text-align:right;min-width:135px}.pro-world b{font-size:11px}.pro-world span{display:block;font-size:9px;color:var(--p-muted);margin-top:2px}
  .pro-boss{position:absolute;top:94px;left:50%;transform:translateX(-50%);width:min(88vw,540px);padding:11px 14px;display:none}.pro-boss .boss-head{display:flex;justify-content:space-between;gap:10px;font-weight:900;font-size:12px}.boss-bar{height:10px;background:#2a1420;border-radius:99px;overflow:hidden;margin:7px 0}.boss-bar i{display:block;height:100%;width:100%;background:linear-gradient(90deg,#ff516d,#ff9b54);box-shadow:0 0 16px rgba(255,81,109,.35)}.boss-meta{display:flex;justify-content:space-between;font-size:9px;color:#d7bfd0}.boss-enrage{color:#ff8aa0}
  .pro-base{position:absolute;left:10px;bottom:86px;width:210px;padding:9px 11px}.pro-base .row{display:flex;justify-content:space-between;font-size:10px;font-weight:800}.hpbar{height:7px;margin-top:6px;border-radius:99px;background:rgba(255,255,255,.07);overflow:hidden}.hpbar i{display:block;height:100%;background:linear-gradient(90deg,#4de2a4,#63e6ff);width:100%}
  .pro-nav{position:absolute;left:50%;bottom:max(9px,env(safe-area-inset-bottom));transform:translateX(-50%);width:min(96vw,690px);display:grid;grid-template-columns:repeat(5,1fr);gap:7px;padding:7px;border-radius:21px;background:rgba(4,10,18,.9);border:1px solid var(--p-line);box-shadow:0 16px 36px rgba(0,0,0,.35);backdrop-filter:blur(18px);pointer-events:auto}.pro-nav button{border:0;background:transparent;color:#9fb1c9;min-height:52px;border-radius:16px;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:3px;font-size:9px;font-weight:800;cursor:pointer;touch-action:manipulation}.pro-nav button .ico{font-size:18px;line-height:1}.pro-nav button.active{color:#fff;background:linear-gradient(180deg,rgba(60,103,145,.5),rgba(24,43,64,.65));box-shadow:inset 0 1px rgba(255,255,255,.08)}
  .pro-build{position:absolute;right:10px;bottom:86px;width:min(56vw,300px);padding:8px;display:flex;gap:6px;pointer-events:auto;overflow-x:auto}.pro-build button{flex:1;min-width:82px;border:1px solid var(--p-line);border-radius:13px;color:#fff;background:linear-gradient(180deg,rgba(26,45,68,.94),rgba(10,21,34,.94));padding:8px 7px;font-size:10px;font-weight:900;box-shadow:0 5px 14px rgba(0,0,0,.22);touch-action:manipulation}.pro-build button small{display:block;color:var(--p-muted);font-size:8px;margin-top:3px}
  .pro-panel{position:absolute;left:50%;top:92px;transform:translateX(-50%);width:min(92vw,520px);max-height:calc(100vh - 180px);overflow:auto;padding:14px;display:none;pointer-events:auto}.pro-panel.show{display:block}.pro-title{display:flex;justify-content:space-between;align-items:center;gap:10px;margin-bottom:10px}.pro-title h2{font-size:15px;margin:0}.pro-close{border:1px solid var(--p-line);background:rgba(255,255,255,.04);color:#fff;width:30px;height:30px;border-radius:10px;cursor:pointer}.pro-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px}.pro-item{padding:10px;border-radius:14px;background:linear-gradient(180deg,rgba(18,34,52,.8),rgba(8,18,30,.78));border:1px solid var(--p-line)}.pro-item h3{font-size:11px;margin:0 0 5px}.pro-item p{font-size:9px;color:var(--p-muted);margin:0 0 8px;line-height:1.5}.pro-item .meta{font-size:9px;color:#c8d7e8;display:flex;justify-content:space-between;gap:6px}.pro-action{margin-top:8px;width:100%;border:0;border-radius:10px;padding:8px;background:linear-gradient(90deg,#2d6c8f,#4a4c90);color:#fff;font-weight:900;font-size:10px;touch-action:manipulation}.pro-action:disabled{opacity:.36}.pro-pill{display:inline-flex;padding:3px 6px;border-radius:99px;background:rgba(255,255,255,.06);color:#c6d6e8;font-size:8px}.rar-common{color:#cbd5e1}.rar-uncommon{color:#7ee8aa}.rar-rare{color:#70c9ff}.rar-epic{color:#c9a0ff}.rar-legendary{color:#ffd166}
  .pro-toast-host{position:absolute;left:50%;top:148px;transform:translateX(-50%);display:flex;flex-direction:column;gap:7px;align-items:center}.pro-toast{pointer-events:none;padding:9px 13px;border-radius:12px;background:rgba(6,12,20,.95);border:1px solid var(--p-line);box-shadow:0 12px 26px rgba(0,0,0,.26);font-size:11px;font-weight:800;animation:pro-in .2s ease,pro-out .25s ease 2.55s forwards}@keyframes pro-in{from{opacity:0;transform:translateY(-6px)}to{opacity:1;transform:none}}@keyframes pro-out{to{opacity:0;transform:translateY(-5px)}}
  @media(max-width:520px){.pro-top{grid-template-columns:1fr auto;}.pro-world{grid-column:1/-1;justify-self:stretch;text-align:left;display:flex;justify-content:space-between;align-items:center}.pro-wave{position:absolute;right:0;top:0}.pro-status{padding-right:145px}.pro-build{left:10px;right:10px;width:auto}.pro-base{bottom:150px;width:180px}.pro-panel{top:132px}}
  `;document.head.appendChild(s);},
  _build(){const root=document.createElement('div');root.id='pro-ui';root.innerHTML=`<div class="pro-top"><div class="pro-card pro-status"><div class="label">المستوى</div><div class="value" id="pu-level">LV 1</div><div class="pro-xp"><i id="pu-xp"></i></div></div><div class="pro-card pro-wave"><b id="pu-wave">الموجة 0</b><span id="pu-wave-state">الاستعداد</span></div><div class="pro-card pro-world"><b id="pu-weather">سماء صافية</b><span id="pu-event">العالم هادئ</span></div></div><div class="pro-card pro-boss" id="pu-boss"><div class="boss-head"><span id="pu-boss-name">حارس الأعماق</span><span id="pu-boss-hp">0 / 0</span></div><div class="boss-bar"><i id="pu-boss-fill"></i></div><div class="boss-meta"><span id="pu-boss-phase">المرحلة 1</span><span id="pu-boss-ability">قدرة جاهزة</span></div></div><div class="pro-card pro-base"><div class="row"><span>حصن الأعماق</span><span id="pu-base-text">100 / 100</span></div><div class="hpbar"><i id="pu-base-fill"></i></div></div><div class="pro-card pro-build" id="pu-build"></div><div class="pro-card pro-panel" id="pu-panel"></div><div class="pro-toast-host" id="pu-toasts"></div><nav class="pro-nav" id="pu-nav"></nav>`;document.body.appendChild(root);this.root=root;this.panel=root.querySelector('#pu-panel');this.nav=root.querySelector('#pu-nav');this.toastHost=root.querySelector('#pu-toasts');this.bossPanel=root.querySelector('#pu-boss');this.buildTray=root.querySelector('#pu-build');this.worldCard=root.querySelector('.pro-world'); this.worldCard.style.cursor='pointer'; this.worldCard.style.pointerEvents='auto'; this.worldCard.onclick=()=>this._worldPanel(); this.baseCard=root.querySelector('.pro-base');this._buildNav();this._buildTray();},
  _buildNav(){const items=[['home','الرئيسية'],['tower','الدفاعات'],['merge','الدمج'],['collection','المجموعة'],['quest','المهام']];this.nav.innerHTML='';for(const [id,label] of items){const b=document.createElement('button');b.dataset.id=id;b.innerHTML=`<span class="ico">${this.icons[id]}</span><span>${label}</span>`;b.onclick=()=>this.open(id);this.nav.appendChild(b);}},
  _buildTray(){this.buildTray.innerHTML='';const types=(CONFIG?.DEFENSES?.TYPES)||{};for(const [id,t] of Object.entries(types)){const b=document.createElement('button');b.dataset.defense=id;b.innerHTML=`${t.icon||'◈'} ${t.name}<small>🪙 ${t.cost} · مدى ${t.range}</small>`;b.onclick=()=>{if(!ProgressionSystem.isUnlocked('defenses',id)){this.toast('هذا الدفاع لم يُفتح بعد');return;} if(DefenseManager.isPlacing) DefenseManager.cancelPlacement(); else DefenseManager.startPlacement(id);this.update();};this.buildTray.appendChild(b);}},
  _bind(){if(typeof EventBus==='undefined')return; const refresh=()=>this.update();EventBus.on('BaseHealthChanged',p=>{if(p){this._base={hp:Number(p.hp)||0,maxHp:Number(p.maxHp)||100};this.update();}});['CurrencyChanged','BaseHealthChanged','ProgressionChanged','WaveStarted','WaveCompleted','BaseHealthChanged','BossSpawned','BossPhaseChanged','BossEnraged','BossDefeated','DefensePlaced','CollectionChanged','CollectionUnlocksChanged','MergeCompleted','QuestStateChanged','QuestProgressChanged','QuestCompleted','QuestRewardClaimed','WorldStateChanged','WorldUpdated','AdvancedWorldStateChanged'].forEach(e=>EventBus.on(e,refresh));},
  _panelShell(title,body){this.panel.innerHTML=`<div class="pro-title"><h2>${title}</h2><button class="pro-close" type="button">×</button></div>${body}`;this.panel.querySelector('.pro-close').onclick=()=>this.close();this.panel.classList.add('show');},
  open(id){this.activePanel=id;this.nav.querySelectorAll('button').forEach(b=>b.classList.toggle('active',b.dataset.id===id));if(id==='home'){this.close();return;}if(id==='tower')this._towerPanel();if(id==='merge')this._mergePanel();if(id==='collection')this._collectionPanel();if(id==='quest')this._questPanel();},
  close(){this.activePanel=null;this.panel.classList.remove('show');this.nav.querySelectorAll('button').forEach(b=>b.classList.remove('active'));},
  _towerPanel(){const types=CONFIG.DEFENSES.TYPES||{};let body='<div class="pro-grid">';for(const [id,t] of Object.entries(types)){const unlocked=ProgressionSystem.isUnlocked('defenses',id);body+=`<article class="pro-item"><h3>${t.icon||'◈'} ${t.name}</h3><p>${unlocked?'متاح لبناء هذا الدفاع.':'مقفل — تقدم في المستويات لفتحه.'}</p><div class="meta"><span>${unlocked?'جاهز':'مستوى لاحق'}</span><span>🪙 ${t.cost}</span></div><button class="pro-action" ${unlocked?'':'disabled'} data-build="${id}">${unlocked?'وضع الدفاع':'مقفل'}</button></article>`;}body+='</div>';this._panelShell('ترسانة الدفاع',body);this.panel.querySelectorAll('[data-build]').forEach(b=>b.onclick=()=>{DefenseManager.startPlacement(b.dataset.build);this.close();});},
  _mergePanel(){const rec=CONFIG.MERGE?.RECIPES||{};let body='<div class="pro-grid">';for(const [id,r] of Object.entries(rec)){const check=MergeSystem.canMerge(id);const input=Object.entries(r.inputs).map(([x,n])=>`${CollectionSystem.getDefinition(x)?.name||x} × ${n}`).join(' + ');const result=CollectionSystem.getDefinition(r.result.itemId)?.name||r.result.itemId;body+=`<article class="pro-item"><h3>✧ ${r.name}</h3><p>${input} → <b>${result}</b></p><div class="meta"><span>المستوى ${r.requiredLevel}</span><span>🪙 ${r.cost}</span></div><button class="pro-action" data-merge="${id}" ${check.ok?'':'disabled'}>${check.ok?'دمج الآن':'غير متاح'}</button></article>`;}body+='</div>';this._panelShell('مختبر الدمج',body);this.panel.querySelectorAll('[data-merge]').forEach(b=>b.onclick=()=>{const r=MergeSystem.merge(b.dataset.merge);if(r.ok)this.toast('تمت عملية الدمج بنجاح');else this.toast('تحتاج موارد أو مستوى أعلى');this.open('merge');});},
  _collectionPanel(){const defs=CollectionSystem.getDefinitions();let body='<div class="pro-grid">';for(const [id,d] of Object.entries(defs)){const unlocked=CollectionSystem.isUnlocked(id),qty=CollectionSystem.getQuantity(id),lvl=CollectionSystem.getUpgradeLevel(id);body+=`<article class="pro-item"><h3>${d.name}</h3><p>${d.category} · <span class="rar-${String(d.rarity||'common').toLowerCase()}">${d.rarity||'Common'}</span></p><div class="meta"><span>الكمية ×${qty}</span><span>ترقية ${lvl}/${d.maxUpgradeLevel||1}</span></div>${unlocked&&qty>0&&lvl<(d.maxUpgradeLevel||1)?`<button class="pro-action" data-up="${id}">ترقية بـ ${25*lvl} 🪙</button>`:''}</article>`;}body+='</div>';this._panelShell('المجموعة',body);this.panel.querySelectorAll('[data-up]').forEach(b=>b.onclick=()=>{const id=b.dataset.up;if(EconomySystem.canAfford(Number(b.textContent.match(/\d+/)?.[0]||25))){const lvl=CollectionSystem.getUpgradeLevel(id)||0;const cost=25*Math.max(1,lvl);if(EconomySystem.spend(cost))CollectionSystem.setUpgradeLevel(id,lvl+1,'ui-upgrade');}this.open('collection');});},
  _questPanel(){const qs=QuestSystem.getQuests();let body='<div>';if(!qs.length)body+='<div class="pro-item">لا توجد مهام</div>';for(const q of qs){body+=`<article class="pro-item" style="margin-bottom:8px"><div class="meta"><b>${q.name}</b><span>${q.progress}/${q.target}</span></div><p>${q.description}</p>${q.completed?`<button class="pro-action" data-claim="${q.questId}" ${q.claimed?'disabled':''}>${q.claimed?'تم الاستلام':'استلام المكافأة'}</button>`:''}</article>`;}body+='</div>';this._panelShell('المهام',body);this.panel.querySelectorAll('[data-claim]').forEach(b=>b.onclick=()=>{QuestSystem.claimQuestReward(b.dataset.claim);this.open('quest');});},
  update(){if(!this.initialized)return;const p=ProgressionSystem?.state?.player||{level:1,xp:0};const need=ProgressionSystem?.xpToNextLevel?.()||100;this.root.querySelector('#pu-level').textContent=`LV ${p.level}`;this.root.querySelector('#pu-xp').style.width=`${Math.max(0,Math.min(100,p.xp/need*100))}%`;const w=WaveOrchestrator?.getUIData?.()||{wave:0,state:'idle',countdown:0,remaining:0};this.root.querySelector('#pu-wave').textContent=w.wave?`الموجة ${w.wave}`:'الموجة 0';this.root.querySelector('#pu-wave-state').textContent=w.state==='countdown'?`تبدأ خلال ${w.countdown}ث`:w.state==='spawning'||w.state==='waiting-clear'?`أعداء متبقون ${w.remaining}`:'الاستعداد';const base=this._base||{hp:100,maxHp:100};this.root.querySelector('#pu-base-text').textContent=`${Math.ceil(base.hp)} / ${Math.ceil(base.maxHp)}`;this.root.querySelector('#pu-base-fill').style.width=`${Math.max(0,Math.min(100,base.hp/base.maxHp*100))}%`;this._boss();this._refreshPanel();},
  _boss(){const d=BossSystem?.getUIData?.();if(!d?.active){this.bossPanel.style.display='none';return;}this.bossPanel.style.display='block';this.root.querySelector('#pu-boss-name').textContent=d.name;this.root.querySelector('#pu-boss-hp').textContent=`${Math.ceil(d.hp)} / ${Math.ceil(d.maxHp)}`;this.root.querySelector('#pu-boss-fill').style.width=`${Math.max(0,Math.min(100,d.ratio*100))}%`;this.root.querySelector('#pu-boss-phase').textContent=`المرحلة ${d.phase}${d.enraged?' · غاضب':''}`;this.root.querySelector('#pu-boss-ability').textContent=d.abilityReadyIn>0?`القدرة بعد ${d.abilityReadyIn.toFixed(1)}ث`:'القدرة جاهزة';},
  _refreshPanel(){if(!this.activePanel)return;const id=this.activePanel;if(id==='tower')this._towerPanel();else if(id==='merge')this._mergePanel();else if(id==='collection')this._collectionPanel();else if(id==='quest')this._questPanel();},
  _worldPanel(){const w=WorldSystem?.getSnapshot?.();const aw=AdvancedWorldSystem?.state?.advancedWorld||{};const rule=AdvancedWorldSystem?.getActiveMapRule?.();const visits=Object.entries(aw.npcVisits||{}).map(([id,n])=>{const d=(CONFIG.ADVANCED_WORLD?.NPCS||[]).find(x=>x.id===id);return `${d?.name||id}: ${n}`}).join('<br>')||'لم تزر أي شخصية بعد';this._panelShell('العالم المتقدم',`<article class=\"pro-item\"><h3>\"الطقس الحالي\"</h3><p>${w?.weather?.name||'-'} · ضوء ${Math.round((w?.daylightFactor||0)*100)}%</p><div class=\"meta\"><span>الأحداث الديناميكية</span><span>${aw.dynamicEventCount||0}</span></div></article><article class=\"pro-item\" style=\"margin-top:8px\"><h3>الشخصيات</h3><p>${visits}</p><div class=\"meta\"><span>قاعدة الخريطة</span><span>${rule?.description||'لا توجد قاعدة خاصة'}</span></div></article>`);},
  updateWorld(){const w=WorldSystem?.getSnapshot?.();if(!w)return;this.root.querySelector('#pu-weather').textContent=w.weather?.name||'العالم';this.root.querySelector('#pu-event').textContent=w.activeEventId?`حدث نشط · ${Math.ceil(w.eventRemaining)}ث`:`الضوء ${Math.round(w.daylightFactor*100)}%`;},
  toast(msg){if(!this.toastHost)return;const e=document.createElement('div');e.className='pro-toast';e.textContent=msg;this.toastHost.appendChild(e);setTimeout(()=>e.remove(),2850);}
};
if(typeof globalThis!=='undefined')globalThis.ProUI=ProUI;